#!/bin/bash
echo "Running NPM Installs in all services."
cd microservice-restaurant-front/
npm install --no-optional
cd ../

cd  microservice-frontend/
npm install --no-optional
cd ../

cd  microservice-customers-api/
npm install --no-optional
cd ../

cd  microservice-orders-api/
npm install --no-optional
cd ../

cd  microservice-restaurants-api/
npm install --no-optional
cd ../


echo "Installation Complete"