version: "3"
services:
  restaurant-reverseproxy:
    build:
      context: .
    image: adamhingoro/restaurant-reverseproxy
  frontend:
    build:
      context: ../../microservice-restaurant-front
    image: adamhingoro/microservice-restaurant-front:latest
  admin-panel:
    build:
      context: ../../microservice-frontend
    image: adamhingoro/microservicefrontend:latest
  restaurant-microservice-users-api:
    build:
      context: ../../microservice-users-api
    image: adamhingoro/restaurant-microservice-users-api:latest
  restaurant-microservice-restaurants-api:
    build:
      context: ../../microservice-restaurants-api
    image: adamhingoro/restaurant-microservice-restaurants-api:latest
  restaurant-microservice-orders-api:
    build:
      context: ../../microservice-orders-api
    image: adamhingoro/restaurant-microservice-orders-api:latest
  restaurant-microservice-customers-api:
    build:
      context: ../../microservice-customers-api
    image: adamhingoro/restaurant-microservice-customers-api:latest
