apiVersion: v1
kind: Service
metadata:
  labels:
    service: admin-panel
  name: admin-panel
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: admin-panel
#  type: LoadBalancer    
