apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
      - image: adamhingoro/microservice-restaurant-front:latest
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always

