apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
      - image: adamhingoro/microservice-restaurant-front:latest
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 5
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always

