apiVersion: v1
kind: Service
metadata:
  labels:
    service: microservice-orders-api
  name: microservice-orders-api
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: microservice-orders-api
