apiVersion: v1
kind: Service
metadata:
  labels:
    service: restaurant-reverseproxy
  name: restaurant-reverseproxy
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - name: "restaurant-endpoint"
    port: 8080
    targetPort: 8080
  selector:
    service: restaurant-reverseproxy
#  type: LoadBalancer    
