apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: restaurant-reverseproxy
  name: restaurant-reverseproxy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        service: restaurant-reverseproxy
    spec:
      containers:
      - image: adamhingoro/restaurant-reverseproxy
        name: restaurant-reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "200m"       
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 5
      restartPolicy: Always


