apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: restaurant-reverseproxy
  name: restaurant-reverseproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: adamhingoro/restaurant-reverseproxy
        name: restaurant-reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


