apiVersion: v1
kind: Service
metadata:
  labels:
    service: restaurant-reverseproxy
  name: restaurant-reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: restaurant-reverseproxy
#  type: LoadBalancer    
